name: Unit testing
on: [push]
jobs:
  run-unit-test:
    runs-on: ubuntu-latest
    container: node:14-alpine
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up node 
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install dependencies
        run: yarn

      - name: Run tests 
        run: yarn test
